# Generated by Django 5.1.4 on 2025-01-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_pic',
            field=models.CharField(default='https://images.app.goo.gl/RRnvPS7GcXofd1DS9', max_length=200),
        ),
    ]
