# Generated by Django 5.1.4 on 2025-02-13 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0002_item_item_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_pic',
            field=models.CharField(default='https://picsum.photos/id/237/536/354', max_length=200),
        ),
    ]
