# Generated by Django 5.0.7 on 2025-03-27 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketManager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketmanager',
            old_name='isPrioriy',
            new_name='isPriority',
        ),
        migrations.RenameField(
            model_name='ticketmanager',
            old_name='tickeid',
            new_name='ticketId',
        ),
        migrations.AddField(
            model_name='ticketmanager',
            name='role',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='TicketManager.rolemodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticketmanager',
            name='clientId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL),
        ),
    ]
