# Generated by Django 5.0.7 on 2025-03-27 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TicketManager', '0003_rename_ispriority_ticketmanager_i3_priority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketmanager',
            old_name='i3_Priority',
            new_name='i3_priority',
        ),
    ]
