# Generated by Django 5.0.7 on 2025-03-27 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TicketManager', '0004_rename_i3_priority_ticketmanager_i3_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rolemodel',
            name='role',
        ),
    ]
