# Generated by Django 5.0.7 on 2025-04-09 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketManager', '0005_remove_rolemodel_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmanager',
            name='clientId',
            field=models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticketmanager',
            name='role',
            field=models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='TicketManager.rolemodel'),
        ),
    ]
