# Generated by Django 5.1.4 on 2025-04-09 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketManager', '0007_alter_authuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmanager',
            name='role',
            field=models.ForeignKey(db_column='role_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='TicketManager.rolemodel'),
        ),
    ]
